export const GO_NEXT = "GO_NEXT";
export const GO_BACK = "GO_BACK";
export const SET_TRANSFER_PIN = "SET_TRANSFER_PIN";
export const SET_TRANSFER_TYPE = "SET_TRANSFER_TYPE";
export const SET_TRANSFER_CARD = "SET_TRANSFER_CARD";
export const SET_TRANSFER_AMOUNT = "SET_TRANSFER_AMOUNT";
export const SET_TRANSFER_IS_CONFIRM = "SET_TRANSFER_IS_CONFIRM";
